---
- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  ignore_errors: true

- name: restart firewall
  ansible.builtin.systemd:
    name: firewall
    state: restarted
  ignore_errors: true